package Overlapping;

public enum DoctorType {
    GENERAL_PRACTITIONER,
    DENTIST,
    OPHTHALMOLOGIST,
    PSYCHIATRIST,
    SURGEON,
    PEDIATRICIAN,
    GYNECOLOGIST,
    ORTHOPEDIST,
    CARDIOLOGIST,
    NEUROLOGIST,
    DERMATOLOGIST,
    RADIOLOGIST,
    ANESTHESIOLOGIST,
    PATHOLOGIST,
    UROLOGIST
}
